import PlanSteadyFalconFormalVerification.Core
import PlanSteadyFalconFormalVerification.GuardedEdit
import PlanSteadyFalconFormalVerification.RunOwnership
import PlanSteadyFalconFormalVerification.McpRegistry
import PlanSteadyFalconFormalVerification.McpLifecycle
import PlanSteadyFalconFormalVerification.VaultPaths
import PlanSteadyFalconFormalVerification.RestoreState
import ProofAudit

#print axioms PlanSteadyFalconFormalVerification.put_same
#print axioms PlanSteadyFalconFormalVerification.put_other
#print axioms PlanSteadyFalconFormalVerification.reachable_invariant
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.ready_has_snapshot
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.guarded_commit
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.conflict_preserves_disk
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.useful_success
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.missing_is_not_empty
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.successful_snapshot
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.other_snapshot_unchanged
#print axioms PlanSteadyFalconFormalVerification.GuardedEdit.failure_preserves_snapshots
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.initial_valid
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.busy_rejects
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.stale_output
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.stale_completion
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.cancellation_invalidates
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.success_starts_one_prompt
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.step_preserves
#print axioms PlanSteadyFalconFormalVerification.RunOwnership.reachable_valid
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.initial_valid
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.collision_rejected
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.useful_registration
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.registration_preserves
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.removal_preserves
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.unique_resolution
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.dispatch_matches_registration
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.stale_dispatch_rejected
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.removed_server_cannot_dispatch
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.reserved_name_rejected
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.ordinary_name_allowed
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.step_preserves
#print axioms PlanSteadyFalconFormalVerification.McpRegistry.reachable_valid
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.initial_valid
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.stale_success_disposed
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.stale_failure_preserves_error
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.unload_cannot_republish
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.useful_connection
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.used_token_cannot_restart
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.disable_reenable_cannot_reuse_attempt
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.failure_invalidates_attempt
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.step_preserves
#print axioms PlanSteadyFalconFormalVerification.McpLifecycle.reachable_valid
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.canonical_idempotent
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.accepted_is_relative
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.accepted_segments_safe
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.skill_beneath
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.empty_folder_rejected
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.empty_segment_folder_rejected
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.skill_requires_canonical_inputs
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.ordinary_note_accepted
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.empty_middle_collapses
#print axioms PlanSteadyFalconFormalVerification.VaultPaths.sibling_prefix_rejected
#print axioms PlanSteadyFalconFormalVerification.RestoreState.interrupted_recovery
#print axioms PlanSteadyFalconFormalVerification.RestoreState.chat_idempotent
#print axioms PlanSteadyFalconFormalVerification.RestoreState.selected_exists
#print axioms PlanSteadyFalconFormalVerification.RestoreState.restore_idempotent
#print axioms PlanSteadyFalconFormalVerification.RestoreState.unique_ids_preserved
#print axioms PlanSteadyFalconFormalVerification.RestoreState.flags_require_true_boolean
#print axioms PlanSteadyFalconFormalVerification.RestoreState.busy_save_unchanged
#print axioms PlanSteadyFalconFormalVerification.RestoreState.save_reads_at_start
#print axioms PlanSteadyFalconFormalVerification.RestoreState.failed_save_retains_last_successful_input
#print axioms PlanSteadyFalconFormalVerification.RestoreState.failed_save_allows_next
#print axioms PlanSteadyFalconFormalVerification.RestoreState.successful_save_records_input

audit_theorems [
  PlanSteadyFalconFormalVerification.put_same,
  PlanSteadyFalconFormalVerification.put_other,
  PlanSteadyFalconFormalVerification.reachable_invariant,
  PlanSteadyFalconFormalVerification.GuardedEdit.ready_has_snapshot,
  PlanSteadyFalconFormalVerification.GuardedEdit.guarded_commit,
  PlanSteadyFalconFormalVerification.GuardedEdit.conflict_preserves_disk,
  PlanSteadyFalconFormalVerification.GuardedEdit.useful_success,
  PlanSteadyFalconFormalVerification.GuardedEdit.missing_is_not_empty,
  PlanSteadyFalconFormalVerification.GuardedEdit.successful_snapshot,
  PlanSteadyFalconFormalVerification.GuardedEdit.other_snapshot_unchanged,
  PlanSteadyFalconFormalVerification.GuardedEdit.failure_preserves_snapshots,
  PlanSteadyFalconFormalVerification.RunOwnership.initial_valid,
  PlanSteadyFalconFormalVerification.RunOwnership.busy_rejects,
  PlanSteadyFalconFormalVerification.RunOwnership.stale_output,
  PlanSteadyFalconFormalVerification.RunOwnership.stale_completion,
  PlanSteadyFalconFormalVerification.RunOwnership.cancellation_invalidates,
  PlanSteadyFalconFormalVerification.RunOwnership.success_starts_one_prompt,
  PlanSteadyFalconFormalVerification.RunOwnership.step_preserves,
  PlanSteadyFalconFormalVerification.RunOwnership.reachable_valid,
  PlanSteadyFalconFormalVerification.McpRegistry.initial_valid,
  PlanSteadyFalconFormalVerification.McpRegistry.collision_rejected,
  PlanSteadyFalconFormalVerification.McpRegistry.useful_registration,
  PlanSteadyFalconFormalVerification.McpRegistry.registration_preserves,
  PlanSteadyFalconFormalVerification.McpRegistry.removal_preserves,
  PlanSteadyFalconFormalVerification.McpRegistry.unique_resolution,
  PlanSteadyFalconFormalVerification.McpRegistry.dispatch_matches_registration,
  PlanSteadyFalconFormalVerification.McpRegistry.stale_dispatch_rejected,
  PlanSteadyFalconFormalVerification.McpRegistry.removed_server_cannot_dispatch,
  PlanSteadyFalconFormalVerification.McpRegistry.reserved_name_rejected,
  PlanSteadyFalconFormalVerification.McpRegistry.ordinary_name_allowed,
  PlanSteadyFalconFormalVerification.McpRegistry.step_preserves,
  PlanSteadyFalconFormalVerification.McpRegistry.reachable_valid,
  PlanSteadyFalconFormalVerification.McpLifecycle.initial_valid,
  PlanSteadyFalconFormalVerification.McpLifecycle.stale_success_disposed,
  PlanSteadyFalconFormalVerification.McpLifecycle.stale_failure_preserves_error,
  PlanSteadyFalconFormalVerification.McpLifecycle.unload_cannot_republish,
  PlanSteadyFalconFormalVerification.McpLifecycle.useful_connection,
  PlanSteadyFalconFormalVerification.McpLifecycle.used_token_cannot_restart,
  PlanSteadyFalconFormalVerification.McpLifecycle.disable_reenable_cannot_reuse_attempt,
  PlanSteadyFalconFormalVerification.McpLifecycle.failure_invalidates_attempt,
  PlanSteadyFalconFormalVerification.McpLifecycle.step_preserves,
  PlanSteadyFalconFormalVerification.McpLifecycle.reachable_valid,
  PlanSteadyFalconFormalVerification.VaultPaths.canonical_idempotent,
  PlanSteadyFalconFormalVerification.VaultPaths.accepted_is_relative,
  PlanSteadyFalconFormalVerification.VaultPaths.accepted_segments_safe,
  PlanSteadyFalconFormalVerification.VaultPaths.skill_beneath,
  PlanSteadyFalconFormalVerification.VaultPaths.empty_folder_rejected,
  PlanSteadyFalconFormalVerification.VaultPaths.empty_segment_folder_rejected,
  PlanSteadyFalconFormalVerification.VaultPaths.skill_requires_canonical_inputs,
  PlanSteadyFalconFormalVerification.VaultPaths.ordinary_note_accepted,
  PlanSteadyFalconFormalVerification.VaultPaths.empty_middle_collapses,
  PlanSteadyFalconFormalVerification.VaultPaths.sibling_prefix_rejected,
  PlanSteadyFalconFormalVerification.RestoreState.interrupted_recovery,
  PlanSteadyFalconFormalVerification.RestoreState.chat_idempotent,
  PlanSteadyFalconFormalVerification.RestoreState.selected_exists,
  PlanSteadyFalconFormalVerification.RestoreState.restore_idempotent,
  PlanSteadyFalconFormalVerification.RestoreState.unique_ids_preserved,
  PlanSteadyFalconFormalVerification.RestoreState.flags_require_true_boolean,
  PlanSteadyFalconFormalVerification.RestoreState.busy_save_unchanged,
  PlanSteadyFalconFormalVerification.RestoreState.save_reads_at_start,
  PlanSteadyFalconFormalVerification.RestoreState.failed_save_retains_last_successful_input,
  PlanSteadyFalconFormalVerification.RestoreState.failed_save_allows_next,
  PlanSteadyFalconFormalVerification.RestoreState.successful_save_records_input]
